##===- unittests/AST/Makefile ---------------------------*- Makefile -*-===##
#
# Copyright (C) 2010 yabin @ CGCL
# HuaZhong University of Science and Technology, China
#
##===----------------------------------------------------------------------===##

LEVEL = ../..
TESTNAME = AST
LINK_COMPONENTS := core support

include $(LEVEL)/Makefile.common
include $(LEVEL)/unittests/Makefile.unittest
