##===- projects/mlang/lib/Makefile -------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL = ..

#
# List all of the subdirectories that we will compile.
#
DIRS = Basic Diag Lex AST Sema Parse Serialization Index \
       Frontend FrontendTool CodeGen Driver

include $(LEVEL)/Makefile.common
