##===- unittests/Lex/Makefile ---------------------------*- Makefile -*-===##
#
# Copyright (C) 2010 yabin @ CGCL
# HuaZhong University of Science and Technology, China
#
##===----------------------------------------------------------------------===##

LEVEL = ../..
TESTNAME = Lex
LINK_COMPONENTS := core support
USEDLIBS := mlangFrontend.a mlangLex.a mlangBasic.a mlangDiag.a

include $(LEVEL)/Makefile.common
include $(LEVEL)/unittests/Makefile.unittest
