##===- unittests/Makefile ----------------------------------*- Makefile -*-===##
#
# Copyright (C) 2010 yabin @ CGCL
# HuaZhong University of Science and Technology, China
#
##===----------------------------------------------------------------------===##

LEVEL = ..

PARALLEL_DIRS = Basic AST Lex Sema Parse Frontend

include $(LEVEL)/Makefile.common

clean::
	$(Verb) $(RM) -f *Tests
