##===- projects/mlang/include/Makefile ---------------------*- Makefile -*-===##

#
# Indicates our relative path to the top of the project's root directory.
#
LEVEL = ..
DIRS = mlang

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
